require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Email in development: by default don't actually deliver — preview rendered
  # mail at http://localhost:3001/rails/mailers instead. To send real mail
  # locally (e.g. to test Resend), set the SMTP_* env vars and it switches to
  # live SMTP automatically.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }
  config.action_mailer.show_previews        = true
  config.action_mailer.preview_paths        << Rails.root.join("spec/mailers/previews").to_s
  # Surface SMTP errors locally — silent failures are worse than loud ones when
  # you're actively testing delivery (e.g. Resend sandbox rejections).
  config.action_mailer.raise_delivery_errors = true
  if ENV["SMTP_HOST"].present?
    config.action_mailer.delivery_method    = :smtp
    config.action_mailer.perform_deliveries = true
    config.action_mailer.smtp_settings = {
      address:              ENV["SMTP_HOST"],
      port:                 ENV.fetch("SMTP_PORT", 587).to_i,
      user_name:            ENV["SMTP_USER"],
      password:             ENV["SMTP_PASS"],
      authentication:       :plain,
      enable_starttls_auto: true
    }
  else
    config.action_mailer.perform_deliveries = false
  end
end
